### ISSUE TITLE
Include backend URL in 'config_deploy.js'

### ISSUE THREAD

**Issue by michael-franke** [babe-project/MinimalTemplate#13]
Currently, the server URL is set in 'main.js' but this should be part of 'config_deploy.js'.

Distribute this change also to other templates/examples.

Include this description in the documentation on the babe-site (MF's job).

**Comment by x-ji** [comment]
The repo is created at https://github.com/babe-project/DynamicDataTemplate. Maybe you'd also want to take a look to confirm it works and change some wordings in the README.

**Comment by stelaseldano** [comment]
The following repos now have the URL in config_deploy.js:

- MinimalTemplate,
- ProlificDeployTemplate,
- MTurkDeployTemplate,
- ResponseTypeTemplate,
- CanvasTemplate
