### ISSUE TITLE
make email obligatory in 'config_deploy.js' and remove ours as a default

### ISSUE THREAD

**Issue by michael-franke** [babe-project/MinimalTemplate#14]
The user's own email should be obligatory in 'config_deploy.js'. Currently, in 'scripts/submit_to_server.js' in line 10, ours is set as a default if no other email is specified. This should be removed. 
Ideally, if no email is specified in 'config_deploy.js', there should be an alert box pop up on the first screen, which can be clicked away, so that everything will work eventually even without an email. The code 'submit_to_server.js' should then be amended to set 'contactEmail' to "No-email-address-provided"

**Comment by JannisBush** [comment]
Done [here](https://github.com/babe-project/babe-project)
