### ISSUE TITLE
Change the submission format to fit the new backend 

### ISSUE THREAD

**Issue by x-ji** [babe-project/MinimalTemplate#9]
- Change of submission URL to `/api/submit_experiment/:id` where `:id` is a number that will be given on the server at experiment creation.
- `author`, `description`, `experiment_id` are no longer necessary following the above change. Only the actual contents will need to be submitted.
- Instead of relying on `trials` key, submit a JSON array directly whose entries contain the same set of keys. The frontend will need to do the job of duplicating the original one-time keys from `other_info`.

Submissions so far:
```json

{
    "experiment_id": "MinimalTemplateDEMO",
    "author": "RandomJane",
    "timeSpent": 0.07485,
    "trials": [
        {
            "option_chosen": "here",
            "RT": 506
        },
        {
            "option_chosen": "jam",
            "RT": 110
        },
        {
            "option_chosen": "fine",
            "RT": 573
        },
        {
            "option_chosen": "jam",
            "RT": 122
        }
    ],
}
```

Expected submissions in the future:
```json
[
    {
        "option_chosen": "here",
        "RT": 506,
        "timeSpent": 0.07485
    },
    {
        "option_chosen": "jam",
        "RT": 110,
        "timeSpent": 0.07485
    },
    {
        "option_chosen": "fine",
        "RT": 573,
        "timeSpent": 0.07485
    },
    {
        "option_chosen": "jam",
        "RT": 122,
        "timeSpent": 0.07485
    }
]
```

**Comment by michael-franke** [comment]
Basic functionality is implemented; currently commented out (see main.js line 219).

**Comment by x-ji** [comment]
For some reason `_.merge(data, t);` will make all objects in the array be based on the last trial. Changing it to `_.merge(t, data)` seems to have fixed the issue.

**Comment by x-ji** [comment]
`_.merge` mutates the first argument. Therefore we would probably want to mutate `t` instead of `data`. If we mutate `data`, then only the last mutation will be kept, which is the merging with the last trial.

https://lodash.com/docs/4.17.5#merge
